### ISSUE TITLE
New in TAPoR 3 Section Not Filled Out

### ISSUE THREAD

**Issue by GZielke** [arcualberta/TAPoR#11]
The "New in TAPoR 3" section isn't well filled-out. It only has the words "Tool lists" and "Code as tools" in it, and the paragraph isn't centered.

**Comment by lagoan** [comment]
Paragraph follows original design.
"New in TAPoR 3" section and paragraph content need to be provided.

**Comment by GZielke** [comment]
I have little write-ups for this, but I can't edit the page directly. I'll email you the blurbs now.
