### ISSUE TITLE
The number after the results page is confusing

### ISSUE THREAD

**Issue by gregws** [arcualberta/TAPoR#116]
![confusing number](https://cloud.githubusercontent.com/assets/22187885/18969019/9b2ea5fc-8648-11e6-9449-4978df433241.png)

I found it confusing that TAPoR displays the total number of tools beside the search results. Right now I think the layout/text is implying 51 pages of results, not X pages of results that have 51 tools.

**Comment by lagoan** [comment]
The search result does not provide the total number of tools, but rather the total number of pages from the search result.

@gregws The screenshot provided should be read as page 6 of 51 in total.

**Comment by gregws** [comment]
It seems to be showing the number of tools, not pages, though. On the screenshot above, "Page 6" is the last page of results I got from the search.
