### ISSUE TITLE
Dark Blue Text Colour

### ISSUE THREAD

**Issue by gregws** [arcualberta/TAPoR#123]
The blue colour for the tag cloud and TAPoR 3 logo and copyright notice is too dark, causing legibility issues. Replace it with the lighter blue used for “Discover research tools for studying texts”.
<img width="316" alt="pastedgraphic-2" src="https://cloud.githubusercontent.com/assets/22187885/19832258/6a8a5c74-9ddc-11e6-96cf-047e6a182247.png">

**Comment by gregws** [comment]
Has the website been updated? Or just the code? I just checked this on chrome/firefox now and both are showing the darker blue tint still.

**Comment by lagoan** [comment]
Just the code. I will be modifying the test site today to reflect these
changes.


Omar

+

**Comment by gregws** [comment]
Great, thanks for clarifying! Just wanted to make sure I wasn't missing something.

**Comment by gregws** [comment]
The text colour is still the dark blue.

**Comment by gregws** [comment]
Sorry I had been checking the tapor.ca not tapor-test.artsrn.ualberta.ca
