### ISSUE TITLE
TAPoR Page - Help Displaying Old Information

### ISSUE THREAD

**Issue by GZielke** [arcualberta/TAPoR#14]
The Help TAPoR page at the top of the toolbar is displaying a page designed for TAPoR 2.5. It needs to be updated for TAPoR 3.0

**Comment by lagoan** [comment]
Content will be edited by administrators.

**Comment by GZielke** [comment]
This is no longer a link on the toolbar. Should we close it?

**Comment by GZielke** [comment]
Page removed from the website, no longer an issue.
