### ISSUE TITLE
Usability Issue - Dragging Tools in Add List

### ISSUE THREAD

**Issue by GZielke** [arcualberta/TAPoR#15]
In the Add List function, the right column doesn't extend all the way down the page. If you want to add a tool at the bottom of the left column, you need to click and drag it while scrolling up to the top of the page to place it in a list. If the columns both extended to the bottom of the page, it would be much quicker to add a tool to a list.

**Comment by mpm1** [comment]
Modified the css to use flex boxes. From there we are able to match the height.

**Comment by lagoan** [comment]
The area is visible fixing the entire page vertical length but the draggable area remains fixed.
To test this try to drag a tool from the bottom of the left list to the right list.

**Comment by lagoan** [comment]
@GZielke can you test the tool list creation view and close this issue if the new layout solves this problem?

**Comment by GZielke** [comment]
This works! The tools drag back and forth really smoothly now.
