### ISSUE TITLE
Tools not appearing in tool list and search

### ISSUE THREAD

**Issue by GZielke** [arcualberta/TAPoR#23]
Tools aren't appearing when you click the Tool tab on the top menu bar. As well, tools aren't appearing in the search bar regardless of what you search for (keywords, tags, etc.).

**Comment by lagoan** [comment]
We need to recreate the index.

@mpm1 please run the following on the rails console

```
XapianDb.rebuild_xapian_index
```

**Comment by mpm1** [comment]
At the moment, running this command produces the following error:
ArgumentError:  was expected to be a number

Looking into this further.

**Comment by mpm1** [comment]
The database has now indexed. There were two tools in the system having a average star rating of NULL instead of 0. Once set to 0 the database was able to index.

**Comment by KamalRanaweera** [comment]
This was caused by bad data --  tool entries of ID = 424 and 539 had star_average=NULL. Set them to 0.  XapianDb.rebuild_xapian_index was successful on rails console production.
Fixed.
