### ISSUE TITLE
Organize tool faceting menus

### ISSUE THREAD

**Issue by lagoan** [arcualberta/TAPoR#26]

**Comment by mpm1** [comment]
- Aligned attributes to be three per row.
- Removed the search field since it already existed in the header.

**Comment by lagoan** [comment]
Columns not aligned properly

![screen shot 2015-10-20 at 2 33 33 pm](https://cloud.githubusercontent.com/assets/1537909/10620326/9da4df7a-7737-11e5-900d-5ff2fc24cf59.png)

**Comment by mpm1** [comment]
Modified to set a max width for each of the select fields.
