### ISSUE TITLE
The left-column description in the carousel has scroll bars when there is more space available for text. This was visible on some computers on Chrome

### ISSUE THREAD

**Issue by KamalRanaweera** [arcualberta/TAPoR#32]

**Comment by lagoan** [comment]
@KamalRanaweera Any thoughts on how to best solve this ?
Breaking text and limiting text length ?

**Comment by lagoan** [comment]
Add hidden

**Comment by lagoan** [comment]
Added attempt to fix deployed on http://tapor-test.artsrn.ualberta.ca/ but cannot verify if it is working.
Could @GZielke or @GeoffreyRockwell check if this is fixed ?
