### ISSUE TITLE
We seem to have the problems with the carousel that I thought we had fixed

### ISSUE THREAD

**Issue by lagoan** [arcualberta/TAPoR#65]
![unnamed-1](https://cloud.githubusercontent.com/assets/1537909/12858804/83309526-cc0f-11e5-901d-23038e0b1baa.png)

**Comment by lagoan** [comment]
Note the black box at top and the text of the description.

**Comment by lagoan** [comment]
Need to reprocess tool images and thumbs

**Comment by GZielke** [comment]
I tried to change the picture on the Voyant Knots tool to see if that fixed the problem and it seems to have done so. Should I go through and change all the pictures manually, or is there an upcoming fix?
