### ISSUE TITLE
Search Bar overlaps everything when window is small enough

### ISSUE THREAD

**Issue by GZielke** [arcualberta/TAPoR#66]
When the browser window is made small enough, the website formatting seems to fall apart. This appears to happen on any page.

**Comment by lagoan** [comment]
Search bar overlaps with carousel on this istance

![screen shot 2016-02-05 at 3 38 09 pm](https://cloud.githubusercontent.com/assets/1537909/12861146/7bb47ef2-cc1e-11e5-937b-27c8ef7cf0df.png)
