### ISSUE TITLE
Remove Button on Add List page appearing in the wrong spot

### ISSUE THREAD

**Issue by GZielke** [arcualberta/TAPoR#68]
The "Remove" button to remove tools added to the list appears on the first tool of the list whenever a new tool is added to the list instead of appearing on the tool that was just added. Removing the first tool gets rid of all the "Remove" buttons. Additionally, the "Remove" buttons don't seem to be functional at the moment.

![remove button error](https://cloud.githubusercontent.com/assets/6404427/12875313/93b09004-cda4-11e5-909e-b5cfd1398031.png)

**Comment by lagoan** [comment]
Related to #38
