### ISSUE TITLE
Special Characters replaced by HTML codes in carousel

### ISSUE THREAD

**Issue by GZielke** [arcualberta/TAPoR#72]
Special characters like - and " are being replaced by their HTML codes in the carousel. This isn't happening on the tool page, only on the carousel.

**Comment by lagoan** [comment]
The tool description is entered as html, this can cause problems with layout. For this reason html is being removed on the carousel and thus we get the html codes. Should it be render as html ? @GZielke

**Comment by GZielke** [comment]
If rendering as html is going to cause more issues with the carousel, we can probably leave it alone. Is it possible to put a bit of code that changes the special character codes back into text just for that one spot?
