### ISSUE TITLE
Out of date resources on the Useful Links page

### ISSUE THREAD

**Issue by GZielke** [arcualberta/TAPoR#75]
Both DUCT and the Humbul Humanities Hub are out of date and no longer link to the current site. Should these just be removed?

**Comment by GeoffreyRockwell** [comment]
No, these should then be tagged as historic and the description updated.

best,

Geoffrey R.

**Comment by GZielke** [comment]
Added a historic section to the useful links page and put these under them.

**Comment by lagoan** [comment]
@GZielke the data from tapor.ca has been frozen while I complete the migration to the new tapor. Any changes will need to be reapplied once data migration is complete.

**Comment by lagoan** [comment]
@GZielke can we close this ?

**Comment by GZielke** [comment]
Finally tracked down the relevant URLs and made sure all links are current. Ready to close.
